Repository masagao/potfy, pull requests merged in 2020-09, with the labels that each got.

#96 トップページの横スクロールを修正する
  resources/views/top.blade.php
Labels: bug

#117 Github Apps の test を行う
  .github/auto_assign.yml
  .github/issue-branch.yml
Labels: PR: unreviewed

#119 Github Apps の test を行う
  .github/issue-branch.yml
Labels: PR: unreviewed

#113 利用規約を作成する
  public/assets/css/app.css
  public/assets/js/app.js
  resources/sass/app.scss
  resources/sass/pages/terms/_base.scss
  resources/views/layouts/app.blade.php
  resources/views/terms/services.blade.php
Labels: PR: reviewed-approved

#124 README.mdを改良したい。
  README.md
Labels: PR: unreviewed

#125 URLのコピーのinputタグを消す。
  public/assets/js/app.js
  resources/js/components/UrlCopyComponent.vue
Labels: PR: unreviewed

#126 ユーザーはメールアドレスとパスワードのみで新規登録できる。 #82
  app/Http/Controllers/User/Auth/RegisterController.php
  database/migrations/2014_10_12_000000_create_users_table.php
  resources/views/user/auth/register.blade.php
Labels: PR: reviewed-approved

#132 ポートフォリオカードに投稿ユーザー情報を表示して、ユーザー詳細に飛べる
  resources/views/top.blade.php
  resources/views/user/portfolios/index.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: reviewed-approved

#135 ポートフォリオの文字列リンク化の軽微な修正
  app/Portfolio.php
Labels: PR: unreviewed

#136 GitHubログイン機能
  app/Http/Controllers/User/Auth/LoginController.php
  composer.json
  composer.lock
  config/services.php
  resources/views/user/auth/login.blade.php
  resources/views/user/auth/register.blade.php
  routes/web.php
Labels: PR: unreviewed

#137 データベースの修正
  database/migrations/2020_09_12_215051_create_career_directions_table.php
  database/migrations/2020_09_12_215351_change_career_and_add_some_column_to_users_table.php
Labels: PR: unreviewed

#138 social_accountsテーブルを作成する
  app/Enums/SocialType.php
  database/migrations/2020_09_12_221054_create_social_accounts_table.php
Labels: PR: unreviewed

#139 Twitterログインをした際に、マイページURLがsocial_accountsに保存できる
  app/Http/Controllers/User/Auth/LoginController.php
  app/SocialAccount.php
Labels: PR: unreviewed

#141 GitHubログインをした際に、マイページURLがsocial_accountsに保存できる
  app/Http/Controllers/User/Auth/LoginController.php
Labels: PR: unreviewed

#140 プライバシーポリシーを作成する
  composer.lock
  resources/views/terms/privacy.blade.php
  resources/views/terms/services.blade.php
Labels: PR: reviewed-approved

#144 ユーザーはsocial_accountをマイページで登録、編集できる
  app/Enums/SocialType.php
  app/Http/Controllers/User/UserController.php
  app/User.php
  resources/lang/ja/enums.php
  resources/views/user/profiles/edit.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#145 aタグでtailwindcssが効き、文字が黒いので修正したい。
  app/Portfolio.php
  resources/views/user/portfolios/show.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#153 portfolio投稿のリンクをnullableに
  app/Http/Requests/PortfolioRequest.php
  database/migrations/2020_08_08_080418_create_portfolios_table.php
Labels: PR: unreviewed

#148 Twitter Share Button 設置 + ボタンを整列させる
  public/assets/js/app.js
  resources/js/components/UrlCopyComponent.vue
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#154 ユーザーが自身の情報を登録できる。
  app/Http/Controllers/User/PortfolioController.php
  app/Http/Controllers/User/UserController.php
  app/User.php
  resources/views/user/profiles/edit.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#157 cardの高さ統一、UI変更
  app/Helpers/RoundSentence.php
  composer.json
  public/assets/js/app.js
  resources/views/top.blade.php
  resources/views/user/portfolios/index.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#158 カード詳細のUIを整える
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#159 cardのユーザーの名前が空の時、ゲスト+idを表示
  resources/views/top.blade.php
  resources/views/user/portfolios/index.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#162 ポートフォリオカードの共通化
  resources/views/components/portfolio-card.blade.php
  resources/views/top.blade.php
  resources/views/user/portfolios/index.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#163 Feature/#81 select tab
  app/Http/Controllers/User/CommentController.php
  app/Http/Controllers/User/HistoryController.php
  app/Http/Controllers/User/PortfolioController.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#164 Twitterログイン、GitHubログインのアイコンを設定する
  package-lock.json
  package.json
  public/assets/css/app.css
  public/assets/webfonts/fa-brands-400.eot
  public/assets/webfonts/fa-brands-400.svg
  public/assets/webfonts/fa-brands-400.ttf
  public/assets/webfonts/fa-brands-400.woff
  public/assets/webfonts/fa-brands-400.woff2
  public/assets/webfonts/fa-regular-400.eot
  public/assets/webfonts/fa-regular-400.svg
  public/assets/webfonts/fa-regular-400.ttf
  public/assets/webfonts/fa-regular-400.woff
  public/assets/webfonts/fa-regular-400.woff2
  public/assets/webfonts/fa-solid-900.eot
  public/assets/webfonts/fa-solid-900.svg
  public/assets/webfonts/fa-solid-900.ttf
  public/assets/webfonts/fa-solid-900.woff
  public/assets/webfonts/fa-solid-900.woff2
  resources/sass/app.scss
  resources/views/user/auth/login.blade.php
  webpack.mix.js
Labels: PR: unreviewed

#156 全てのユーザーからのURLの投稿をlink化したい。 #106
  app/Comment.php
  app/History.php
  app/Http/Controllers/User/CommentController.php
  app/Http/Controllers/User/HistoryController.php
  app/Http/Controllers/User/StoryController.php
  app/Story.php
  app/User.php
  public/assets/css/app.css
  public/assets/js/app.js
Labels: PR: unreviewed

#168 issue-167-potfy
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#170 issue-169-potfy
  app/Http/Controllers/User/PortfolioController.php
  resources/views/user/portfolios/edit.blade.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#176 ユーザー名が登録されていない時に、トップメニューに「ゲスト+ID」で表示をすることができる
  resources/views/layouts/user/nav.blade.php
Labels: PR: unreviewed

#178 aタグが青くなっていない為、青くしたい。
  resources/views/user/auth/login.blade.php
  resources/views/user/auth/register.blade.php
Labels: PR: unreviewed

#179 新規投稿ボタンは、ログイン中のユーザーのみ見えるようにしたい
  resources/views/layouts/user/nav.blade.php
Labels: PR: reviewed-approved

#180 ユーザーアイコンタブ、マイページとログアウトの順序を変えたい
  resources/views/layouts/user/nav.blade.php
Labels: PR: reviewed-approved

#188 外部リンクに遷移する際に、一応警告を表示したい #187
  .github/wip.yml
  app/Comment.php
  app/History.php
  app/Portfolio.php
  app/Story.php
  app/User.php
Labels: PR: unreviewed

#183 Company の 新規登録機能廃止 #150
  app/Http/Controllers/Company/Auth/RegisterController.php
  public/assets/css/app.css
  resources/views/company/auth/register.blade.php
  routes/web.php
Labels: PR: reviewed-approved

#190 自分の投稿での Twitter シェア を表示しないようにしたい
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#182 OGPを出せるようにしたい。
  app/Http/Controllers/User/CommentController.php
  app/Http/Controllers/User/HistoryController.php
  app/Http/Controllers/User/PortfolioController.php
  app/Http/Controllers/User/StoryController.php
  public/assets/fonts/Roboto-Regular.ttf
  resources/views/components/portfolio-card.blade.php
  resources/views/layouts/header.blade.php
  resources/views/layouts/ogp-meta.blade.php
  resources/views/user/portfolios/show.blade.php
  routes/web.php
Labels: PR: unreviewed

#192 ポートフォリオ詳細のヘッダーが出ていないので、出す
  resources/views/layouts/app.blade.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#196 バリデーション確認
  app/Http/Controllers/User/UserController.php
  app/Http/Requests/PortfolioRequest.php
  app/Http/Requests/StoryRequest.php
  app/Http/Requests/UserRequest.php
  resources/views/user/portfolios/create.blade.php
  resources/views/user/profiles/edit.blade.php
Labels: PR: unreviewed

#201 ポートフォリオ新規投稿ボタンを丸くする
  resources/views/layouts/user/nav.blade.php
Labels: PR: unreviewed

#205 ポートフォリオ一覧画面のページネーションを12で付けたい
  app/Http/Controllers/User/PortfolioController.php
Labels: PR: unreviewed

#209 ストーリー投稿時のタイプの文言を分かりやすくしたい
  resources/lang/ja/enums.php
Labels: PR: unreviewed

#211 開発履歴、ストーリーを投稿者のみが投稿できるようにしました
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#193 投稿されたアプリの詳細に改行があった場合、詳細画面でも改行したい #186
  app/Comment.php
  app/History.php
  app/Portfolio.php
  app/Story.php
  app/User.php
  database/migrations/2020_08_08_080439_create_comments_table.php
  resources/views/components/portfolio-card.blade.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#212 ストーリーやコメント、開発履歴に投稿者の名前が表示されていない
  resources/views/components/portfolio-card.blade.php
  resources/views/layouts/user/nav.blade.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: reviewed-approved

#214 サービス内の投稿日時等の時間表示のフォーマットを diffForHumans(Carbon\Carbon::now()) で統一したい
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#217 Twitter 拡散機能においては、GAOGAOGATE を表示しないようにする
  .github/issue-states.yml
  .github/workflows/opened-pull-wip.yml
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#219 ポートフォリオ詳細のUIを整える
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#220 開発履歴や、ストーリーがないときに、現在投稿はありませんと表示できるようにする
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#222 ユーザー詳細ページには、該当ユーザーの投稿が表示されるようにする
  app/Http/Controllers/User/UserController.php
  resources/views/user/portfolios/show.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#223 技術タグをdatalistで表示し、同一の物は新規作成されないようにする
  app/Http/Controllers/User/PortfolioController.php
  app/Http/Requests/PortfolioRequest.php
  app/Technology.php
  database/migrations/2020_08_17_064050_change_link_add_image_path_and_public_id_to_portfolios_table.php
  package-lock.json
  package.json
  public/assets/css/app.css
  public/assets/js/app.js
  resources/js/app.js
  resources/js/components/SelectComponent.vue
  resources/views/user/portfolios/create.blade.php
  resources/views/user/portfolios/edit.blade.php
Labels: PR: unreviewed

#224 Story コメント は UpdateOrCreate で実装したい
  app/Http/Controllers/User/StoryController.php
  app/Story.php
Labels: PR: unreviewed

#237 Feature/issue 189 potfy
  app/History.php
  app/Http/Controllers/User/CommentController.php
  app/Http/Controllers/User/HistoryController.php
  app/Http/Controllers/User/StoryController.php
  app/Story.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: reviewed-approved

#238 ゲストにはコメント欄を表示しない
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#242 新規登録画面のUIを整えたい
  public/assets/css/app.css
  public/assets/js/app.js
  resources/views/user/auth/login.blade.php
  resources/views/user/auth/register.blade.php
  tailwind.config.js
Labels: PR: unreviewed

#245 ユーザー詳細のプロフィール編集ボタンは、ログインユーザーのみに表示する
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#246 ポートフォリオ編集、新規投稿（言語複数選択にプレイスホルダーを設定したい）
  public/assets/js/app.js
  resources/js/components/SelectComponent.vue
  resources/views/user/auth/login.blade.php
  resources/views/user/auth/register.blade.php
Labels: PR: unreviewed

#243 user.users を解消しつつ、ログインしていなくても ユーザー詳細が閲覧できる
  app/Http/Controllers/User/UserController.php
  app/Http/Middleware/Authenticate.php
  resources/views/components/portfolio-card.blade.php
  resources/views/layouts/user/nav.blade.php
  resources/views/user/portfolios/show.blade.php
  resources/views/user/profiles/edit.blade.php
  resources/views/user/profiles/show.blade.php
  routes/web.php
Labels: PR: reviewed-approved

#248 aタグが青くなっていないため、ボタンを押せるのかを判断しにくい
  resources/views/user/portfolios/show.blade.php
  resources/views/user/profiles/edit.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#253 ユーザーIDに関してもランダムな文字数列に変更したい。 #225
  app/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2020_08_08_080418_create_portfolios_table.php
  database/migrations/2020_08_08_080439_create_comments_table.php
  database/migrations/2020_09_02_023919_create_histories_table.php
  database/migrations/2020_09_02_030511_create_stories_table.php
  database/migrations/2020_09_12_215051_create_career_directions_table.php
  database/migrations/2020_09_12_221054_create_social_accounts_table.php
Labels: PR: reviewed-approved

#206 マイページ詳細画面で、画像の設定がない場合にdefaultの画像が出せる
  resources/views/user/portfolios/edit.blade.php
  resources/views/user/profiles/edit.blade.php
  resources/views/user/profiles/show.blade.php
Labels: PR: reviewed-approved

#255 ポートフォリオの画像保存サイズを修正
  app/Http/Controllers/User/PortfolioController.php
Labels: PR: reviewed-approved

#256 ユーザー詳細画面で、紹介文に改行が反映されていないので、反映させる
  resources/views/user/profiles/show.blade.php
Labels: PR: reviewed-approved

#258 技術タグをみやすく表示したい・oldの反映
  database/seeds/TechnologiesTableSeeder.php
  public/assets/js/app.js
  resources/js/components/SelectComponent.vue
  resources/views/user/portfolios/create.blade.php
  resources/views/user/portfolios/edit.blade.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: unreviewed

#260 ユーザー編集画面のユーザー画像を正円で表示できる
  resources/views/user/portfolios/show.blade.php
  resources/views/user/profiles/edit.blade.php
Labels: PR: unreviewed

#265 ユーザー詳細のGithub, Twitter, Wantedly を文字表示からアイコン表示に変更する
  public/assets/css/app.css
  public/assets/image/wantedly_mark.png
  public/assets/js/app.js
  resources/sass/app.scss
  resources/sass/user/_user_profiles_show.scss
  resources/views/user/profiles/show.blade.php
Labels: PR: unreviewed

#267 ストーリー、開発履歴、コメントのエラーメッセージ日本語化
  app/Http/Controllers/User/CommentController.php
  app/Http/Controllers/User/HistoryController.php
  app/Http/Requests/CommentRequest.php
  app/Http/Requests/HistoryRequest.php
  app/Http/Requests/StoryRequest.php
  resources/lang/ja/validation.php
Labels: PR: reviewed-approved

#269 パスワード変更機能（Gmail）
  app/Http/Controllers/User/Auth/ForgotPasswordController.php
  app/Http/Controllers/User/Auth/ResetPasswordController.php
  app/Notifications/PasswordResetNotification.php
  app/User.php
  resources/views/user/auth/login.blade.php
  resources/views/user/auth/passwords/email.blade.php
  resources/views/user/auth/passwords/reset.blade.php
  routes/web.php
Labels: PR: unreviewed

#273 view側で繰り返し登場する条件式を、変数に変更する
  app/Http/Controllers/User/PortfolioController.php
  resources/views/user/portfolios/show.blade.php
Labels: PR: reviewed-approved

#274 運営ページを作成する
  app/Http/Controllers/TermsController.php
  resources/views/layouts/footer.blade.php
  resources/views/terms/organizer.blade.php
Labels: PR: reviewed-approved

#268 uuidが長すぎるので短くしたい。
  app/Portfolio.php
  app/User.php
  composer.json
  composer.lock
Labels: PR: unreviewed

#277 トップページの見出しUIの修正
  resources/views/top.blade.php
Labels: PR: unreviewed

#279 運営メンバーチームUIの軽微な修正
  resources/views/terms/organizer.blade.php
Labels: PR: unreviewed
